const CopyPlugin = require('copy-webpack-plugin');
const config = require('./webpack.config');
const ZipperPlugin = require('./zipper-plugin');
const path = require('path');
const WebpackObfuscator = require('webpack-obfuscator');

const SKETCH_ENTRYPOINT = process.env['SKETCH_ENTRYPOINT'];

if (!SKETCH_ENTRYPOINT) {
  throw new Error(`Environment variable SKETCH_ENTRYPOINT was not defined`);
}

module.exports = {
  ...config,
  mode: 'production',
  // add the zipper plugin to the list of plugins
  plugins: [
    ...config.plugins,
    new WebpackObfuscator(
      {
        rotateStringArray: true
      },
      []
    ),
    new CopyPlugin({
      patterns: [
        {
          from: 'public',
          // prevents the index.html from being copied to the the public folder, as it's going to be
          // generated by webpack
          filter: async (filePath) => {
            return path.basename(filePath) !== 'index.html';
          }
        }
      ]
    }),
    new ZipperPlugin({
      outputPath: path.resolve(path.dirname(SKETCH_ENTRYPOINT), 'dist/project.zip')
    })
  ]
};
