name: CI

on:
  push:
    branches: ['main']

jobs:
  blog:
    name: Observable blog
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./notebook
        run: npm install

      - name: Build
        working-directory: ./notebook
        run: npm run build
        env:
          GA_ID: ${{ secrets.GA_ID }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PERSONAL_TOKEN }}
          publish_dir: ./notebook/dist
          cname: tronica.io
